[package]
name = "ecs-trie"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1.0"
fasthash = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "trie_benches"
harness = false

[lib]
bench = false
